name: RPGMood
version: 1.1.1
main: com.ricardo.rpgmood.RPGMoodPlugin
api-version: '1.20'
author: Ricardo
softdepend: [PlaceholderAPI, WorldGuard]
commands:
  rpgmood:
    description: Main RPGMood commands
    usage: /rpgmood <reload|toggle [titles]|info|leaderboard [deaths|zones|level]>
  diary:
    description: Opens the player's adventure journal
    usage: /diary
    aliases: [diario]
    permission: rpgmood.player.diary
permissions:
  rpgmood.admin:
    default: op
  rpgmood.player.diary:
    default: true
  rpgmood.player.toggle:
    default: true
  rpgmood.player.leaderboard:
    default: true
